{
 "title": "Farming Simulator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prom", "label": "prom", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Vehicles",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fs_vehicles_age", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Farmland Owned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(fs_farmlands == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Amount of Mods Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fs_total_amount_mods", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Money",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Euro" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fs_amount_of_money", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time Played",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fs_total_time_played", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Missions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fs_mission{Status=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Money",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "fs_amount_of_money", "legendFormat": "{{Name}}" }
   ]
  },
  {
   "title": "Land Owned/Not Owned",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(fs_farmlands == 0)", "legendFormat": "Not Owned" },
    { "expr": "count(fs_farmlands == 1)", "legendFormat": "Owned" }
   ]
  },
  {
   "title": "Mission Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "fs_mission{Status=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missions",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fs_mission{Status=\"0\"})",
     "legendFormat": "Available Missions"
    },
    {
     "expr": "count(fs_mission{Status=\"1\"})",
     "legendFormat": "Active Missions"
    }
   ]
  }
 ]
}